create table event
(
    id        integer generated by default as identity
        primary key,
    subject   varchar not null,
    organizer varchar not null,
    time      timestamp with time zone,
    place     varchar not null
);

alter table event
    owner to postgres;

